services:
  splunk:
    image: splunk/splunk:latest
    container_name: splunk
    ports:
      - "8000:8000"   # Web UI
      - "8088:8088"   # HEC (HTTP Event Collector)
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=changeme
    volumes:
     - /var/log/honeypot.log:/mnt/honeypot.log
     - /var/log/targetvm.log:/mnt/targetvm.log 
    restart: unless-stopped
